target-version = "py314"
 
line-length = 80
indent-width = 4
 
src = ["src"]
 
[lint]
preview = true
select = ["ALL"]

ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D107",
    "CPY001",
    "W292",
    "W293",
    "COM812"
]

exclude = [
    "tests/**",
]

fixable = [
    "I",
]
 

[format]
quote-style = "double"
indent-style = "space"
 

[lint.flake8-bandit]
check-typed-exception = true
