target-version = "py314"
 
line-length = 80
indent-width = 4
 
src = ["src"]
 
[lint]
preview = true
select = ["ALL"]

ignore = [
    "D",
    "CPY001",
    "W292",
    "W293",
    "COM812",
    "INP001",
    "UP042",
    "S311",
    "RUFF067"
]

exclude = [
    "tests/**",
]

fixable = [
    "I",
]
 

[format]
quote-style = "double"
indent-style = "space"
 

[lint.flake8-bandit]
check-typed-exception = true
